### ISSUE TITLE
Double Damage description not found in non english language

### ISSUE THREAD

**Issue by EnderBoyHUN** [Plajer-Lair/Village_Defense#9]
**Describe the bug**
If you playing in non English (e.g. German, Hungarian) and pickup double damage, then powerup's descriptions not found.
 
**Steps to reproduce**
Holographic Displays required
1. Set the ```locate``` value to  e.g. ```de``` or ```hu``` in ```config.yml```
2. Reload the server
3. Join an arena
4. Kill zombie while not drop _double damage_ powerup (error on console)
5. Pick up the powerup 
6. See error on title

**Error**
```
[19:40:17 WARN]: java.lang.NullPointerException
[19:40:18 WARN]:        at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324)
[19:40:18 WARN]:        at pl.plajer.villagedefense3.handlers.ChatManager.colorMessage(ChatManager.java:47)
[19:40:18 WARN]:        at pl.plajer.villagedefense3.handlers.PowerupManager.spawnPowerup(PowerupManager.java:109)
[19:40:18 WARN]:        at pl.plajer.villagedefense3.arena.ArenaEvents.onDieEntity(ArenaEvents.java:109)
[19:40:18 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:40:18 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:40:18 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:40:18 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[19:40:18 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[19:40:18 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[19:40:18 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[19:40:18 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[19:40:18 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:395)
[19:40:18 WARN]:        at net.minecraft.server.v1_12_R1.EntityLiving.die(EntityLiving.java:1116)
[19:40:18 WARN]:        at net.minecraft.server.v1_12_R1.EntityZombie.die(EntityZombie.java:429)
[19:40:18 WARN]:        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:956)
[19:40:18 WARN]:        at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44)
[19:40:18 WARN]:        at net.minecraft.server.v1_12_R1.EntityZombie.damageEntity(EntityZombie.java:163)
[19:40:18 WARN]:        at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1005)
[19:40:18 WARN]:        at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1311)
[19:40:18 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1621)
[19:40:18 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69)
[19:40:18 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13)
[19:40:18 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[19:40:18 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[19:40:18 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[19:40:18 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[19:40:18 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[19:40:18 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[19:40:18 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[19:40:18 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[19:40:18 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:40:18 INFO]:   _____                                                                                  _   _
[19:40:18 INFO]:  | ____|  _ __   _ __    ___    _ __      ___     ___    ___   _   _   _ __    ___    __| | | |
[19:40:18 INFO]:  |  _|   | '__| | '__|  / _ \  | '__|    / _ \   / __|  / __| | | | | | '__|  / _ \  / _` | | |
[19:40:18 INFO]:  | |___  | |    | |    | (_) | | |      | (_) | | (__  | (__  | |_| | | |    |  __/ | (_| | |_|
[19:40:18 INFO]:  |_____| |_|    |_|     \___/  |_|       \___/   \___|  \___|  \__,_| |_|     \___|  \__,_| (_)
[19:40:18 INFO]:
[19:40:18 INFO]: Game message not found!
[19:40:18 INFO]: Please regenerate your language.yml file! If error still occurs report it to the developer!
[19:40:18 INFO]: Access string: Powerups.Double-Damage-Powerup.Description
```

**Environment:**
 - Server version: [e.g. 1.12.2]
 - Plugin version: [e.g. 3.8.1]
 - Plugins list: HD and WorldEdit

**Attachment**
German:
![2018-07-12_19 28 49](https://user-images.githubusercontent.com/12803062/42651193-0066fb3c-860f-11e8-9d1f-aac5e901f51c.png)
Hungarian:
![2018-07-12_19 40 22](https://user-images.githubusercontent.com/12803062/42651194-009b4572-860f-11e8-887d-5fa54f7919d9.png)

**Comment by Plajer** [comment]
Thanks for the report! Will be fixed asap.
